// 云函数：年度总结
const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })

const db = cloud.database()
const _ = db.command

exports.main = async (event, context) => {
  const { OPENID } = cloud.getWXContext()
  const { action, year } = event

  switch (action) {
    case 'generate':
      return await generateYearlySummary(OPENID, year)
    case 'getYearList':
      return await getYearList(OPENID)
    case 'getYearData':
      return await getYearData(OPENID, year)
    default:
      return { success: false, error: '未知操作' }
  }
}

// 生成年度总结
async function generateYearlySummary(openid, year) {
  try {
    if (!year) {
      year = new Date().getFullYear()
    }

    // 检查是否已存在
    const existing = await db.collection('yearly_summaries')
      .where({ _openid: openid, year: year })
      .get()

    if (existing.data.length > 0) {
      // 更新现有记录
      const summaryData = await calculateYearlyData(openid, year)
      await db.collection('yearly_summaries')
        .doc(existing.data[0]._id)
        .update({
          data: {
            summaryData,
            updateTime: db.serverDate()
          }
        })
      return { success: true, data: { year, isUpdate: true } }
    } else {
      // 创建新记录
      const summaryData = await calculateYearlyData(openid, year)
      await db.collection('yearly_summaries').add({
        data: {
          _openid: openid,
          year,
          summaryData,
          createTime: db.serverDate(),
          updateTime: db.serverDate(),
          isAutoGenerated: false
        }
      })
      return { success: true, data: { year, isUpdate: false } }
    }
  } catch (err) {
    console.error('生成年度总结失败：', err)
    return { success: false, error: err.message }
  }
}

// 计算年度数据
async function calculateYearlyData(openid, year) {
  try {
    // 获取该年度的所有账单
    const bills = []
    let hasMore = true
    let page = 1
    const pageSize = 100

    while (hasMore) {
      const res = await db.collection('bills')
        .where({
          _openid: openid,
          date: _.gte(`${year}-01-01`).and(_.lte(`${year}-12-31`))
        })
        .skip((page - 1) * pageSize)
        .limit(pageSize)
        .get()

      if (res.data.length === 0) {
        hasMore = false
      } else {
        bills.push(...res.data)
        if (res.data.length < pageSize) {
          hasMore = false
        } else {
          page++
        }
      }
    }

    // 统计数据
    let totalIncome = 0
    let totalExpense = 0
    const bookkeepingDates = new Set()
    const expenseByCategory = {}
    const monthlyData = {}

    // 初始化12个月的数据
    for (let m = 1; m <= 12; m++) {
      const key = String(m).padStart(2, '0')
      monthlyData[key] = { month: m, income: 0, expense: 0, count: 0 }
    }

    bills.forEach(bill => {
      // 记录记账日期
      if (bill.date) {
        bookkeepingDates.add(bill.date)
      }

      // 计算收入
      if (bill.type === 'income') {
        totalIncome += (bill.amount || 0)
      }

      // 计算支出
      if (bill.type === 'expense') {
        totalExpense += (bill.amount || 0)

        // 统计支出分类
        const category = bill.category || '其他'
        const icon = bill.icon || '📦'
        if (!expenseByCategory[category]) {
          expenseByCategory[category] = { name: category, icon, amount: 0 }
        }
        expenseByCategory[category].amount += (bill.amount || 0)
      }

      // 按月份聚合（用于月度趋势）
      if (bill.date) {
        const parts = bill.date.split('-')
        const month = (parts[1] || '0').padStart(2, '0')
        if (monthlyData[month]) {
          if (bill.type === 'income') {
            monthlyData[month].income += bill.amount
          } else {
            monthlyData[month].expense += bill.amount
          }
          monthlyData[month].count += 1
        }
      }
    })

    // 计算日均消费/收入
    const daysInYear = isLeapYear(year) ? 366 : 365
    const dailyAvgExpense = (totalExpense / daysInYear).toFixed(2)
    const dailyAvgIncome = (totalIncome / daysInYear).toFixed(2)

    // 计算储蓄率
    let savingsRate = 0
    if (totalIncome > 0) {
      savingsRate = Math.round(((totalIncome - totalExpense) / totalIncome) * 100)
    }

    // 计算记账频率
    const avgBillsPerDay = (bills.length / daysInYear).toFixed(1)

    // 计算记账率
    const bookkeepingRate = Math.round((bookkeepingDates.size / daysInYear) * 100)

    // 处理支出分类排行
    const expenseRankList = Object.values(expenseByCategory)
      .sort((a, b) => b.amount - a.amount)
      .slice(0, 10)
      .map(item => ({
        ...item,
        amountStr: item.amount.toFixed(2),
        percent: totalExpense > 0 ? Math.round((item.amount / totalExpense) * 100) : 0
      }))

    // 处理月度趋势数据
    const monthlyTrend = Object.values(monthlyData)
      .sort((a, b) => a.month - b.month)
      .map(item => {
        const expense = item.expense || 0
        const income = item.income || 0
        const balance = income - expense
        return {
          ...item,
          expenseStr: expense.toFixed(2),
          incomeStr: income.toFixed(2),
          balanceStr: balance.toFixed(2),
          balance
        }
      })

    // 计算Y轴刻度（用于前端图表）
    let maxMonthlyAmount = 0
    monthlyTrend.forEach(item => {
      const total = (item.expense || 0) + (item.income || 0)
      if (total > maxMonthlyAmount) maxMonthlyAmount = total
    })

    const yAxisLabels = []
    for (let i = 4; i >= 0; i--) {
      const value = maxMonthlyAmount * (i / 4)
      yAxisLabels.push(value.toFixed(2))
    }

    return {
      totalIncome,
      totalExpense,
      totalCount: bills.length,
      bookkeepingDays: bookkeepingDates.size,
      dailyAvgExpense,
      dailyAvgIncome,
      savingsRate,
      avgBillsPerDay,
      bookkeepingRate,
      expenseRankList,
      // 月度趋势数据
      monthlyTrend,
      maxMonthlyAmount,
      yAxisLabels
    }
  } catch (err) {
    console.error('计算年度数据失败：', err)
    throw err
  }
}

// 判断是否是闰年
function isLeapYear(year) {
  return (year % 4 === 0 && year % 100 !== 0) || (year % 400 === 0)
}

// 获取有数据的年度列表
async function getYearList(openid) {
  try {
    const currentYear = new Date().getFullYear()
    const yearList = []

    // 1. 查询 yearly_summaries 表中已有的历史年度总结
    const summaries = await db.collection('yearly_summaries')
      .where({ _openid: openid })
      .field({ year: true })
      .get()

    const yearsWithSummary = new Set()
    summaries.data.forEach(s => {
      if (s.year && s.year < currentYear) {
        yearsWithSummary.add(s.year)
      }
    })

    // 添加历史年度（有年度总结的）
    yearsWithSummary.forEach(year => {
      yearList.push({
        year,
        hasData: true,
        hasSummary: true,
        desc: '已有年度总结'
      })
    })

    // 2. 检查当年是否有账单数据
    const currentYearBills = await db.collection('bills')
      .where({
        _openid: openid,
        date: _.gte(`${currentYear}-01-01`).and(_.lte(`${currentYear}-12-31`))
      })
      .field({ date: true })
      .limit(1)
      .get()

    if (currentYearBills.data.length > 0) {
      // 当年有账单数据，添加到列表
      yearList.push({
        year: currentYear,
        hasData: true,
        hasSummary: yearsWithSummary.has(currentYear),
        desc: yearsWithSummary.has(currentYear) ? '已有年度总结' : '今年（可生成总结）'
      })
    }

    // 按年份降序排序
    yearList.sort((a, b) => b.year - a.year)

    console.log('获取到的年度列表：', yearList)
    return { success: true, data: yearList }
  } catch (err) {
    console.error('获取年度列表失败：', err)
    return { success: false, error: err.message }
  }
}

// 获取指定年度数据
async function getYearData(openid, year) {
  try {
    if (!year) {
      return { success: false, error: '请指定年份' }
    }

    const currentYear = new Date().getFullYear()

    if (year < currentYear) {
      // 历史年度：从 yearly_summaries 表读取
      const summary = await db.collection('yearly_summaries')
        .where({ _openid: openid, year: year })
        .get()

      if (summary.data.length > 0) {
        console.log(`从数据库读取 ${year} 年度总结`)
        return { success: true, data: summary.data[0].summaryData }
      } else {
        // 历史年度没有总结，自动生成并保存（兜底机制）
        console.log(`${year} 年度无总结，自动生成中...`)
        const summaryData = await calculateYearlyData(openid, year)
        await db.collection('yearly_summaries').add({
          data: {
            _openid: openid,
            year,
            summaryData,
            createTime: db.serverDate(),
            updateTime: db.serverDate(),
            isAutoGenerated: true // 标记为自动生成
          }
        })
        console.log(`已自动生成 ${year} 年度总结`)
        return { success: true, data: summaryData }
      }
    } else {
      // 当年：从 bills 表实时计算
      console.log(`实时计算 ${year} 年度数据`)
      const summaryData = await calculateYearlyData(openid, year)
      return { success: true, data: summaryData }
    }
  } catch (err) {
    console.error('获取年度数据失败：', err)
    return { success: false, error: err.message }
  }
}
